name: layout_grids
description: Visual aids for grid systems, which can be used to ensure that your UI conforms to your desired grid layout.
version: 0.2.0
homepage: https://github.com/doppio/layout_grids

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
